# Generated by Django 5.2.17 on 2026-09-26 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_project_starred_by'),
        ('main', '0007_seed_editor_account'),
    ]

    operations = [
    ]
