# Generated by Django 5.2.17 on 2026-09-27 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_merge_20260926_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='thumbnail',
        ),
    ]
