# Generated by Django 5.2.17 on 2026-09-28 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_experience_starred_by'),
        ('main', '0011_update_editor_password'),
    ]

    operations = [
    ]
